version: '3.8'

services:
  web:
    build:
      context: .
      args:
        MODE: development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1