version: '3'
services:
  web:
    build:
      context: .
      args:
        MODE: development
    volumes:
      - .:/fisch_oder_finte
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development